# Generated by Django 2.1.7 on 2019-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presenter', models.TextField()),
                ('title', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='presentations')),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('attending', models.BooleanField(default=True)),
            ],
        ),
    ]
